apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: apiapp
spec:
  selector:
    app: first-app
  ports:
    - protocol: 'TCP'
      port: 5002
      targetPort: 5002
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-app
  labels:
    group: apiapp
spec:
  replicas: 10
  selector:
    matchExpressions:
      - { key: app, operator: In, values: [first-app, second-app] }
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
        - name: first-node
          image: farhanmirza/hello-app:2.0
          livenessProbe:
            httpGet:
              path: /
              port: 5002
            periodSeconds: 10
            initialDelaySeconds: 5
